name: PR Deployment

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to the latest version

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Updated to the latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Run Docker container
        run: docker run -d --name my-app-${{ github.sha }} -p 8080:80 my-app:${{ github.sha }}

      - name: Update Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: |
          docker stop my-app-${{ github.sha }}
          docker rm my-app-${{ github.sha }}
          docker run -d --name my-app-${{ github.sha }} -p 8080:80 my-app:${{ github.sha }}

      - name: Cleanup Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          docker stop my-app-${{ github.sha }}
          docker rm my-app-${{ github.sha }}

      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"body": "Deployment successful: http://3.21.156.158:8080"}' \
            ${{ github.event.pull_request.comments_url }}

